### ISSUE TITLE
execute `yarn` ,Can't not response https://raw.githubusercontent.com/pancakeswap/token-list/main/lists/pancakeswap-extended.json 

### ISSUE THREAD

**Issue by Clickcheng110110** [VenusProtocol/venus-protocol-interface#1640]
such as the follow screenshot
![image](https://github.com/VenusProtocol/venus-protocol-interface/assets/136178955/450693b7-60ea-48bb-8175-f0f572741bf7)

**Comment by therealemjy** [comment]
Hi @Clickcheng110110 

Thanks for your interest. This might have been due to a temporary issue with GitHub, you can see the files being fetched [here](https://raw.githubusercontent.com/pancakeswap/token-list/main/lists/pancakeswap-extended.json). You should be able to run the `yarn` command and get the postinstall script to run succesfully.

Feel free to open another issue if the problem persists.
