### ISSUE TITLE
venus subgraph not working

### ISSUE THREAD

**Issue by wxw1111** [VenusProtocol/venus-protocol-interface#496]
https://thegraph.com/hosted-service/subgraph/venusprotocol/venus-subgraph

**Comment by wxw1111** [comment]
"errors": [{"message": "indexing_error"}]

**Comment by coreyar** [comment]
Thanks bringing this to our attention. This is not an updated or maintained deployment of the Venus subgraph. The last update was over 1 year ago.

**Comment by coreyar** [comment]
Actually after consulting with the smart-contracts team, this is a known issue related to the Terra/UST incident.

**Comment by kkirka** [comment]
Yeah, thank you @wxw1111! Although currently we don't maintain `venusprotocol/venus-subgraph`, we still have plans to fix it or provide a replacement. The error occurred because we turned off the price feeds for the assets when we dealt with the LUNA/UST incident – the subgraph expected the prices to always be well defined. We will update you once we have a fix for it.

Are you using it in your application? We want to make sure we don't miss any requirement, so if you could tell us about your data needs, it would be really helpful.

**Comment by DeCiM20** [comment]
If i cant get the account data through subgraph from where can i get the data of how much i have supplied etc?

**Comment by coreyar** [comment]
Apologies for the delay. The subgraph has been redeployed and has finished reindexing. You can view it [here](https://thegraph.com/hosted-service/subgraph/venusprotocol/venus-subgraph) in the hosted studio

We will maintain this subgraph going forward. The code can be found [here](https://github.com/VenusProtocol/subgraphs/tree/master/subgraphs/venus)
